import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { ROLES, CLASS_YEARS as YEARS } from '../lib/roles'
import BrandMark from '../components/BrandMark'

const SEMESTERS = ['Spring 2026', 'Fall 2026', 'Spring 2027', 'Fall 2027']

const inputCls = 'gl-input'

function Field({ label, children }) {
  return (
    <div>
      <label className="block text-[13px] font-medium mb-1.5" style={{ color: '#5b677f' }}>{label}</label>
      {children}
    </div>
  )
}

function Spin() {
  return (
    <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
    </svg>
  )
}

export default function CompleteSetup() {
  const navigate = useNavigate()
  const { user, refreshProfile, signOut } = useAuth()

  const meta = user?.user_metadata ?? {}
  const metaName = meta.full_name || user?.email || ''

  // Pre-select the mode the user chose at signup, so finishing is one click.
  const [mode, setMode] = useState(meta.flow === 'join' ? 'join' : meta.flow === 'create' ? 'create' : null)
  const [saving, setSaving] = useState(false)
  const [error, setError]   = useState(null)

  const [createForm, setCreateForm] = useState({
    chapterName: meta.chapter_name || '',
    semester:    meta.semester || 'Fall 2026',
    role:        meta.role || 'Treasurer',
  })
  const [joinForm, setJoinForm] = useState({
    joinCode: meta.join_code || '',
    year:     meta.year || 'Freshman',
  })

  const setC = (k, v) => { setCreateForm((f) => ({ ...f, [k]: v })); setError(null) }
  const setJ = (k, v) => { setJoinForm((f) => ({ ...f, [k]: v }));   setError(null) }

  // Always pull the user id straight from the session — never from context,
  // which can momentarily lag right after signup.
  async function currentUserId() {
    const { data: { session }, error: sErr } = await supabase.auth.getSession()
    if (sErr || !session?.user) throw new Error('Your session expired. Please sign in again.')
    return { id: session.user.id, email: session.user.email }
  }

  async function handleCreate() {
    if (!createForm.chapterName.trim()) { setError('Chapter name is required.'); return }
    setSaving(true); setError(null)
    try {
      const { id: userId, email } = await currentUserId()

      // join_code is generated by the DB default (gen_join_code()).
      const { data: chapter, error: chapErr } = await supabase
        .from('chapters')
        .insert({
          name:       createForm.chapterName.trim(),
          semester:   createForm.semester,
          created_by: userId,
        })
        .select()
        .single()
      if (chapErr) throw new Error(`Could not create chapter: ${chapErr.message}`)

      const { error: memErr } = await supabase
        .from('members')
        .insert({
          chapter_id:  chapter.id,
          user_id:     userId,
          full_name:   metaName,
          role:        createForm.role,
          year:        'Senior',
          dues_status: 'Paid',
          email,
        })
      if (memErr) throw new Error(`Could not create your member record: ${memErr.message}`)

      await refreshProfile()
      navigate('/', { replace: true })
    } catch (err) {
      setError(err?.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  async function handleJoin() {
    if (joinForm.joinCode.trim().length !== 6) { setError('Enter the 6-character join code.'); return }
    setSaving(true); setError(null)
    try {
      const { id: userId, email } = await currentUserId()

      const { data: rows, error: lookupErr } = await supabase
        .rpc('lookup_join_code', { code: joinForm.joinCode.toUpperCase().trim() })
      if (lookupErr) throw new Error(`Join code lookup failed: ${lookupErr.message}`)
      if (!rows?.length) throw new Error('Invalid join code. Check with your treasurer and try again.')

      const { error: memErr } = await supabase
        .from('members')
        .insert({
          chapter_id:  rows[0].chapter_id,
          user_id:     userId,
          full_name:   metaName,
          role:        'Member',
          year:        joinForm.year,
          dues_status: 'Pending',
          email,
        })
      if (memErr) throw new Error(`Could not join the chapter: ${memErr.message}`)

      await refreshProfile()
      navigate('/', { replace: true })
    } catch (err) {
      setError(err?.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-12" style={{ backgroundColor: '#f3efe6' }}>
      <div className="mb-8 gl-rise"><BrandMark variant="dark" size="md" /></div>

      <div className="gl-card rounded-2xl w-full max-w-md overflow-hidden gl-rise" style={{ animationDelay: '0.08s' }}>
        <div className="px-9 pt-9 pb-6 text-center" style={{ borderBottom: '1px solid #e9e2d3' }}>
          <p className="gl-eyebrow mb-3" style={{ color: '#b08d4f' }}>Almost there</p>
          <h1 className="gl-serif mb-2" style={{ fontSize: '1.85rem', fontWeight: 600, color: '#1b2640' }}>Complete Your Setup</h1>
          <p className="text-sm" style={{ color: '#5b677f' }}>
            One last step — set up your chapter, then you are in.
          </p>
          {user?.email && <p className="text-xs mt-3" style={{ color: '#a99f8b' }}>Signed in as {user.email}</p>}
        </div>

        <div className="px-9 py-7 space-y-4">
          {error && (
            <p className="text-sm px-4 py-3 rounded-lg" style={{ backgroundColor: '#fbeaea', color: '#9b2c2c', border: '1px solid #f0d2d2' }}>{error}</p>
          )}

          {!mode && (
            <div className="space-y-3">
              <button
                onClick={() => { setMode('create'); setError(null) }}
                className="group w-full flex items-center gap-4 p-4 rounded-xl text-left transition gl-card hover:-translate-y-0.5"
              >
                <div className="flex-shrink-0 w-11 h-11 rounded-lg flex items-center justify-center" style={{ backgroundColor: '#1b2640' }}>
                  <svg className="w-5 h-5" fill="none" stroke="#c4a368" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.6} d="M12 4v16m8-8H4" />
                  </svg>
                </div>
                <div className="flex-1">
                  <p className="gl-serif" style={{ fontSize: '1.1rem', fontWeight: 600, color: '#1b2640' }}>Create a Chapter</p>
                  <p className="text-[12.5px] mt-0.5" style={{ color: '#5b677f' }}>I am a treasurer or officer setting up our chapter.</p>
                </div>
                <span className="transition group-hover:translate-x-0.5" style={{ color: '#b08d4f' }}>→</span>
              </button>

              <button
                onClick={() => { setMode('join'); setError(null) }}
                className="group w-full flex items-center gap-4 p-4 rounded-xl text-left transition gl-card hover:-translate-y-0.5"
              >
                <div className="flex-shrink-0 w-11 h-11 rounded-lg flex items-center justify-center" style={{ backgroundColor: '#f6efe0', border: '1px solid #e7dcc4' }}>
                  <svg className="w-5 h-5" fill="none" stroke="#b08d4f" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.6} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </div>
                <div className="flex-1">
                  <p className="gl-serif" style={{ fontSize: '1.1rem', fontWeight: 600, color: '#1b2640' }}>Join a Chapter</p>
                  <p className="text-[12.5px] mt-0.5" style={{ color: '#5b677f' }}>I have a 6-character join code from my treasurer.</p>
                </div>
                <span className="transition group-hover:translate-x-0.5" style={{ color: '#b08d4f' }}>→</span>
              </button>
            </div>
          )}

          {mode === 'create' && (
            <div className="space-y-4">
              <Field label={<>Chapter / Organization Name <span style={{ color: '#b08d4f' }}>*</span></>}>
                <input type="text" placeholder="Alpha Beta — Epsilon Chapter" value={createForm.chapterName}
                  onChange={(e) => setC('chapterName', e.target.value)} className={inputCls} autoFocus />
              </Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Semester">
                  <select value={createForm.semester} onChange={(e) => setC('semester', e.target.value)} className={inputCls}>
                    {SEMESTERS.map((s) => <option key={s}>{s}</option>)}
                  </select>
                </Field>
                <Field label="Your Role">
                  <select value={createForm.role} onChange={(e) => setC('role', e.target.value)} className={inputCls}>
                    {ROLES.map((r) => <option key={r}>{r}</option>)}
                  </select>
                </Field>
              </div>
              <div className="flex gap-3 pt-1">
                <button onClick={() => { setMode(null); setError(null) }} className="flex-1 px-4 py-2.5 rounded-lg text-sm font-medium transition" style={{ color: '#5b677f', border: '1px solid #e3dccd' }}>Back</button>
                <button onClick={handleCreate} disabled={saving || !createForm.chapterName.trim()}
                  className="gl-btn-brass flex-1 px-4 py-2.5 rounded-lg text-sm font-semibold disabled:opacity-50 flex items-center justify-center gap-2">
                  {saving && <Spin />}{saving ? 'Creating…' : 'Create Chapter'}
                </button>
              </div>
            </div>
          )}

          {mode === 'join' && (
            <div className="space-y-4">
              <Field label={<>Join Code <span style={{ color: '#b08d4f' }}>*</span></>}>
                <input type="text" placeholder="ABC123" maxLength={6} value={joinForm.joinCode}
                  onChange={(e) => setJ('joinCode', e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))}
                  className={`${inputCls} gl-serif text-center`}
                  style={{ fontSize: '1.5rem', fontWeight: 600, letterSpacing: '0.4em', paddingLeft: '0.4em' }} autoFocus />
                <p className="text-xs mt-2 text-center" style={{ color: '#a99f8b' }}>{joinForm.joinCode.length}/6 characters</p>
              </Field>
              <Field label="Your Year">
                <select value={joinForm.year} onChange={(e) => setJ('year', e.target.value)} className={inputCls}>
                  {YEARS.map((y) => <option key={y}>{y}</option>)}
                </select>
              </Field>
              <div className="flex gap-3 pt-1">
                <button onClick={() => { setMode(null); setError(null) }} className="flex-1 px-4 py-2.5 rounded-lg text-sm font-medium transition" style={{ color: '#5b677f', border: '1px solid #e3dccd' }}>Back</button>
                <button onClick={handleJoin} disabled={saving || joinForm.joinCode.length !== 6}
                  className="gl-btn-brass flex-1 px-4 py-2.5 rounded-lg text-sm font-semibold disabled:opacity-50 flex items-center justify-center gap-2">
                  {saving && <Spin />}{saving ? 'Joining…' : 'Join Chapter'}
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="px-9 py-4 text-center" style={{ borderTop: '1px solid #e9e2d3' }}>
          <button onClick={signOut} className="text-xs transition hover:opacity-70" style={{ color: '#a99f8b' }}>
            Sign out and use a different account
          </button>
        </div>
      </div>
    </div>
  )
}
