import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'

const SEMESTERS = ['Spring 2026', 'Fall 2026', 'Spring 2027', 'Fall 2027']
const ROLES     = ['Treasurer', 'President', 'VP Finance', 'Secretary', 'Social Chair', 'Member']
const YEARS     = ['Freshman', 'Sophomore', 'Junior', 'Senior', '5th Year']

const inputCls = 'w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'

function Field({ label, children }) {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      {children}
    </div>
  )
}

function Spin() {
  return (
    <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
    </svg>
  )
}

export default function CompleteSetup() {
  const navigate = useNavigate()
  const { user, refreshProfile, signOut } = useAuth()

  const meta = user?.user_metadata ?? {}
  const metaName = meta.full_name || user?.email || ''

  // Pre-select the mode the user chose at signup, so finishing is one click.
  const [mode, setMode] = useState(meta.flow === 'join' ? 'join' : meta.flow === 'create' ? 'create' : null)
  const [saving, setSaving] = useState(false)
  const [error, setError]   = useState(null)

  const [createForm, setCreateForm] = useState({
    chapterName: meta.chapter_name || '',
    semester:    meta.semester || 'Fall 2026',
    role:        meta.role || 'Treasurer',
  })
  const [joinForm, setJoinForm] = useState({
    joinCode: meta.join_code || '',
    year:     meta.year || 'Freshman',
  })

  const setC = (k, v) => { setCreateForm((f) => ({ ...f, [k]: v })); setError(null) }
  const setJ = (k, v) => { setJoinForm((f) => ({ ...f, [k]: v }));   setError(null) }

  // Always pull the user id straight from the session — never from context,
  // which can momentarily lag right after signup.
  async function currentUserId() {
    const { data: { session }, error: sErr } = await supabase.auth.getSession()
    if (sErr || !session?.user) throw new Error('Your session expired. Please sign in again.')
    return { id: session.user.id, email: session.user.email }
  }

  async function handleCreate() {
    if (!createForm.chapterName.trim()) { setError('Chapter name is required.'); return }
    setSaving(true); setError(null)
    try {
      const { id: userId, email } = await currentUserId()

      // join_code is generated by the DB default (gen_join_code()).
      const { data: chapter, error: chapErr } = await supabase
        .from('chapters')
        .insert({
          name:       createForm.chapterName.trim(),
          semester:   createForm.semester,
          created_by: userId,
        })
        .select()
        .single()
      if (chapErr) throw new Error(`Could not create chapter: ${chapErr.message}`)

      const { error: memErr } = await supabase
        .from('members')
        .insert({
          chapter_id:  chapter.id,
          user_id:     userId,
          full_name:   metaName,
          role:        createForm.role,
          year:        'Senior',
          dues_status: 'Paid',
          email,
        })
      if (memErr) throw new Error(`Could not create your member record: ${memErr.message}`)

      await refreshProfile()
      navigate('/', { replace: true })
    } catch (err) {
      setError(err?.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  async function handleJoin() {
    if (joinForm.joinCode.trim().length !== 6) { setError('Enter the 6-character join code.'); return }
    setSaving(true); setError(null)
    try {
      const { id: userId, email } = await currentUserId()

      const { data: rows, error: lookupErr } = await supabase
        .rpc('lookup_join_code', { code: joinForm.joinCode.toUpperCase().trim() })
      if (lookupErr) throw new Error(`Join code lookup failed: ${lookupErr.message}`)
      if (!rows?.length) throw new Error('Invalid join code. Check with your treasurer and try again.')

      const { error: memErr } = await supabase
        .from('members')
        .insert({
          chapter_id:  rows[0].chapter_id,
          user_id:     userId,
          full_name:   metaName,
          role:        'Member',
          year:        joinForm.year,
          dues_status: 'Pending',
          email,
        })
      if (memErr) throw new Error(`Could not join the chapter: ${memErr.message}`)

      await refreshProfile()
      navigate('/', { replace: true })
    } catch (err) {
      setError(err?.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-12" style={{ backgroundColor: '#f8f9fa' }}>
      <div className="flex items-center gap-3 mb-8">
        <div className="flex items-center justify-center w-10 h-10 rounded-xl text-lg font-bold flex-shrink-0" style={{ backgroundColor: '#1e2a4a', color: '#c9a84c' }}>
          &#9730;
        </div>
        <span className="text-xl font-bold tracking-tight" style={{ color: '#1e2a4a' }}>Greek Ledger</span>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 w-full max-w-md overflow-hidden">
        <div className="px-8 pt-8 pb-6 text-center border-b border-gray-100">
          <h1 className="text-xl font-bold text-gray-900 mb-2">Complete Your Setup</h1>
          <p className="text-sm text-gray-500">
            One last step — set up your chapter, then you are in.
          </p>
          {user?.email && <p className="text-xs text-gray-400 mt-3">Signed in as {user.email}</p>}
        </div>

        <div className="px-8 py-6 space-y-4">
          {error && (
            <p className="text-sm px-3 py-2 rounded-lg" style={{ backgroundColor: '#fee2e2', color: '#b91c1c' }}>{error}</p>
          )}

          {!mode && (
            <div className="space-y-3">
              <button
                onClick={() => { setMode('create'); setError(null) }}
                className="w-full flex items-start gap-4 p-4 rounded-xl border-2 text-left transition hover:border-blue-400"
                style={{ borderColor: '#e5e7eb' }}
              >
                <div className="flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center" style={{ backgroundColor: '#eff6ff' }}>
                  <svg className="w-5 h-5" fill="none" stroke="#3b82f6" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-900">Create a Chapter</p>
                  <p className="text-xs text-gray-500 mt-0.5">I am a treasurer or officer setting up our chapter.</p>
                </div>
              </button>

              <button
                onClick={() => { setMode('join'); setError(null) }}
                className="w-full flex items-start gap-4 p-4 rounded-xl border-2 text-left transition hover:border-blue-400"
                style={{ borderColor: '#e5e7eb' }}
              >
                <div className="flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center" style={{ backgroundColor: '#f0fdf4' }}>
                  <svg className="w-5 h-5" fill="none" stroke="#22c55e" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-900">Join a Chapter</p>
                  <p className="text-xs text-gray-500 mt-0.5">I have a 6-character join code from my treasurer.</p>
                </div>
              </button>
            </div>
          )}

          {mode === 'create' && (
            <div className="space-y-4">
              <Field label={<>Chapter / Organization Name <span className="text-red-400">*</span></>}>
                <input type="text" placeholder="Alpha Beta — Epsilon Chapter" value={createForm.chapterName}
                  onChange={(e) => setC('chapterName', e.target.value)} className={inputCls} autoFocus />
              </Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Semester">
                  <select value={createForm.semester} onChange={(e) => setC('semester', e.target.value)} className={inputCls}>
                    {SEMESTERS.map((s) => <option key={s}>{s}</option>)}
                  </select>
                </Field>
                <Field label="Your Role">
                  <select value={createForm.role} onChange={(e) => setC('role', e.target.value)} className={inputCls}>
                    {ROLES.map((r) => <option key={r}>{r}</option>)}
                  </select>
                </Field>
              </div>
              <div className="flex gap-3 pt-1">
                <button onClick={() => { setMode(null); setError(null) }} className="flex-1 px-4 py-2.5 rounded-lg text-sm font-medium text-gray-600 border border-gray-200 hover:bg-gray-50 transition">Back</button>
                <button onClick={handleCreate} disabled={saving || !createForm.chapterName.trim()}
                  className="flex-1 px-4 py-2.5 rounded-lg text-sm font-semibold transition hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
                  style={{ backgroundColor: '#1e2a4a', color: '#fff' }}>
                  {saving && <Spin />}{saving ? 'Creating…' : 'Create Chapter'}
                </button>
              </div>
            </div>
          )}

          {mode === 'join' && (
            <div className="space-y-4">
              <Field label={<>Join Code <span className="text-red-400">*</span></>}>
                <input type="text" placeholder="ABC123" maxLength={6} value={joinForm.joinCode}
                  onChange={(e) => setJ('joinCode', e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))}
                  className={`${inputCls} font-mono text-center text-lg tracking-widest`} autoFocus />
                <p className="text-xs text-gray-400 mt-1 text-center">{joinForm.joinCode.length}/6 characters</p>
              </Field>
              <Field label="Your Year">
                <select value={joinForm.year} onChange={(e) => setJ('year', e.target.value)} className={inputCls}>
                  {YEARS.map((y) => <option key={y}>{y}</option>)}
                </select>
              </Field>
              <div className="flex gap-3 pt-1">
                <button onClick={() => { setMode(null); setError(null) }} className="flex-1 px-4 py-2.5 rounded-lg text-sm font-medium text-gray-600 border border-gray-200 hover:bg-gray-50 transition">Back</button>
                <button onClick={handleJoin} disabled={saving || joinForm.joinCode.length !== 6}
                  className="flex-1 px-4 py-2.5 rounded-lg text-sm font-semibold transition hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
                  style={{ backgroundColor: '#1e2a4a', color: '#fff' }}>
                  {saving && <Spin />}{saving ? 'Joining…' : 'Join Chapter'}
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="px-8 py-4 border-t border-gray-100 text-center">
          <button onClick={signOut} className="text-xs text-gray-400 hover:text-gray-600 transition">
            Sign out and use a different account
          </button>
        </div>
      </div>
    </div>
  )
}
